version: "3.9"

services:
  app:
    container_name: flask_orders_app_prod
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/appdb_prod
