version: "3.9"

services:
  app:
    container_name: flask_orders_app_dev
    environment:
      APP_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:5432/appdb_dev
